<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GEPPARLA-IN" ignored="0" name="Retry Test" tests="3" failures="2" timestamp="12 Dec 2019 04:58:05 GMT" time="0.045" errors="0">
  <testcase name="Test1" time="0.012" classname="eg.ext.practice.RetryAnalyzerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at eg.ext.practice.RetryAnalyzerTest.Test1(RetryAnalyzerTest.java:11)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="eg.ext.practice.RetryAnalyzerTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at eg.ext.practice.RetryAnalyzerTest.Test1(RetryAnalyzerTest.java:11)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.001" classname="eg.ext.practice.RetryAnalyzerTest"/>
</testsuite> <!-- Retry Test -->
